.gitignore
src/project/local_settings.py
src/project/settings.py
src/remote_client_user/middleware.py
src/remote_client_user/tests.py

Changes since to oauth stuff since creating the DRF3 branch.

Dvalp api django18 oauthtoolkit

---

src/sa_api_v2/views/base_views.py
src/sa_api_v2/views/bulk_data_views.py

More updates related to our DRF3 upgrade

DRF3 request module updates

---

src/sa_api_v2/serializers.py

Revert `*_to_representation` back to `*_to_native` until we find a way to properly refactor the new methods

Revert the `*_to_representation` serializer field methods

---

src/sa_api_v2/tests/test_views.py

Django18 drf3 test place instance view 44

---

Dockerfile
requirements.txt
src/sa_api_v2/migrations/0003_auto_20160304_0527.py

Update to latest 1.7 dependencies
Staged and tested. Part of release 0.6.2.

1.7 dependencies upgrade

---

CHANGELOG.md
Dockerfile

Deployment updates

---

doc/README.md

The package dependencies have shifted.  Here is what worked for me.

Setup doc update

---

CHANGELOG.md
doc/README.md

Minor updates to our changelog

Docs config updates

---

src/sa_api_v2/tests/test_views.py
src/sa_api_v2/views/base_views.py

Fix user group permissions 52

---

src/project/settings.py

Reconfigure logging to work with sentry/raven

---

CHANGELOG.md
requirements.txt
src/sa_api_v2/management/commands/migrateLandmarkData.py
src/sa_api_v2/views/base_views.py

Addresses: #60.
- Add a data migration script suitable for GeoJSON data, such as the vision and restoration landmark datasets
- Sanitize submitted data server-side using the [bleach](https://pypi.python.org/pypi/bleach/1.4.3) package

Landmark data migration

---

src/sa_api_v2/views/base_views.py

Previously only the content of POST requests was sanitized.

add HTML sanitizer to PUT requests

---

src/sa_api_v2/views/base_views.py

- allow iframe width and height attributes through the sanitizer

Sanitizer update

---

.travis.yml

Fixes Travis CI build, described here: https://github.com/boto/boto/issues/3741

chore(travis.yml) fix CI build

---

setup.cfg

setup.cfg provides support for linting to have more consistent coding styles. Read more here: http://pep8.readthedocs.io/en/latest/intro.html

style(setup.cfg)

---

src/project/local_settings.py
src/sa_api_v2/models/core.py
src/sa_api_v2/serializers.py
src/sa_api_v2/tasks.py
src/sa_api_v2/tests/test_views.py
src/sa_api_v2/views/base_views.py

This PR fixes the automated tests, but I am sure there are at least 3-4 more problems (if not more). What's our testing strategy? How can we run this against real maps?

Fix tests on DRF3/Django 1.8

---

.circleci/config.yml
Dockerfile

Resolves: https://github.com/jalMogo/mgmt/issues/8
Resolves: https://github.com/jalMogo/mgmt/issues/7
Also addresses some merge issues.

chore(circleci): update tags

---

requirements.txt

workaround for: https://github.com/jalMogo/mgmt/issues/19

chore(requirements.txt): fix dev environment with psycopg2-binary

---

src/sa_api_v2/serializers.py
src/sa_api_v2/tests/test_views.py

Addresses: https://github.com/jalMogo/mgmt/issues/32

fix(PlaceSerializer): update DataSetRelatedField serializer

---

src/sa_api_v2/urls.py
src/sa_api_v2/views/__init__.py
src/sa_api_v2/views/base_views.py
src/sa_api_v2/views/email_templates.py

This PR adds a new route, useful for previewing email HTML templates.
Also refactors the EmailTemplateMixing from base_views into a separate views file.

feat(EmailTemplateDetailView): add view
