- doc/README.md
In documentation, "Local setup" comes before "Database".
However, at least on OS X, running `pip install -r requirements.txt` fails,
mentioning pg_config. But if we execute the steps in the next section titled
"Database", installing postgres etc, the `pip` command succeeds.
> Add note about installation order.

- src/sa_api_v2/serializers.py
- queryset is now a required for non read-only HyperlinkedIdentityField: http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield
- We are getting a new bug for the required 'view_name' argument to PlaceSerializer.url() (PlaceIdentityField)
> Fix 'NameError: name 'queryset' is not defined' error

- src/sa_api_v2/serializers.py
- serializers.HyperlinkedIdentityField and serializers.HyperlinkedRelatedField now require 'view_name' and 'queryset' to be explicitly defined as kwargs
- For these instances, we explicitly define the correct 'view_name' and 'queryset' params as attributes, which are then passed as kwargs to the appropriate rest_framework.serializers field.
- We are now getting an error when calling `pagination.NextPageField(source='*')` on the rest_framework.pagination module: `AttributeError: 'module' object has no attribute 'NextPageField'`
> Explicitly define 'view_name' and 'queryset' attrs

- requirements.txt
- src/sa_api_v2/renderers.py
- src/sa_api_v2/serializers.py
- src/sa_api_v2/views/base_views.py
- Replaced custom `PaginationMetadataSerializer` class with built-in `PageNumberPagination` (http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination)
- Replaced deprecated `pagination_serializer_class` with `pagination_class` (http://www.django-rest-framework.org/topics/3.1-announcement/)
- Using `djangorestframework-jsonp` module (jsonp renderer is no longer built into DRF) and added `from rest_framework_jsonp.renderers import JSONPRenderer`.
> Pagination serializer updates for DRF3.3

- src/sa_api_v2/views/base_views.py
Addresses #52 -- but we should talk about this a bit before merging!
This PR removes the `IsOwnerOrReadOnly` permission class from the list of permission classes in `OwnedResourceMixin`, and moves a check against `permissions.SAFE_METHODS` to the `isAllowedByDataPermissions` class.
It turns out that _all_ permissions in the list of permissions classes must return `True` for the REST Framework to allow a given request (see [here](http://www.django-rest-framework.org/api-guide/permissions/)).
Except in the case of `permissions.SAFE_METHODS`, the `IsOwnerOrReadOnly` permission class will return `False` unless, as the name suggests, the request comes from the a dataset's owner or the dataset is read only.
To support our in-browser editor, we want any number of users who have been added to a …
> Remove IsOwnerOrReadOnly permission class from OwnedResourceMixin

- src/project/local_settings.py
- src/project/settings.py
- src/sa_api_v2/serializers.py
Add Google to our list of supported social auth login options.
I tested this a bit via ngrok, and it seems to work well. Using google requires a process similar to the facebook app creation process, where we have to register domains. We also have to explicitly enable the Google+ API for logins to work.
Once this is merged and deployed I'll add a button on the frontend for Google logins.
> Add google login option

- src/project/settings.py
- src/sa_api_v2/serializers.py
For facebook open graph api versions >= 2.8, apparently the bio field is no longer a valid request parameter. The api reports:
```
(#12) bio field is deprecated for versions v2.8 and higher
```
Requests made with the bio field included will return a 400 error. After removing the bio field from our requests, Facebook logins are working again.
> fix facebook social logins

- src/sa_api_v2/views/base_views.py
To support cross-origin ajax requests with credentials, we have to allow the api to return an Access-Control-Allow-Origin header with the requesting domain set. The more permissive * value for this header won't work. It's a violation of CORS policy to make a cross-origin request with credentials with the Access-Control-Allow-Origin set to the * wildcard.
This PR will make https://github.com/mapseed/platform/pull/807 possible, which moves to the client the proxy-server functionality that attached the appropriate session cookie.
> Allow cross-origin OPTIONS requests to set Access-Control-Allow-Origin header

- src/sa_api_v2/management/commands/migrateRoseGrants.py
- src/sa_api_v2/management/commands/migrateSettledCases.py
These scripts will create two new datasets--`pugetsoundrose` and `pugetsoundcases`--from geojson data stored on github. They're based on the other data ingestion scripts.
Usage:
```
python src/manage.py migrateRoseGrants <username> <email>
python src/manage.py migrateSettledCases <username> <email>
```
where `<username` is the username under which the dataset will be namespaced, and `<email>` is the email address of that user.
> Add Pugetsound data migration scripts

- src/project/local_settings.py
- src/project/settings.py
This PR adds some minor changes to our Django settings, described below:
* There are a few email settings that we are missing, as documented here: https://docs.djangoproject.com/en/1.7/ref/settings/#email-host So this PR adds those missing variables.
* The `.env` in our deployment scripts contains the email settings, which gets parsed in `local_settings.py`, not `settings.py`, so this PR fixes that. If interested, you can see that the `.env` config gets parsed here: https://github.com/mapseed/api/compare/place-email...luke/place-email?expand=1#diff-96acbce0311b17ac0c52c0bd5dadefaaL30
> feat(localSettings) add email notification settings

- src/project/settings.py
Addresses: https://github.com/mapseed/platform/issues/394
**NOTE:** This PR works in conjunction with https://github.com/modulitos/docker-shareabouts/pull/11.
This PR adds two pieces of configuration to `settings.py`:
```
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```
tells Django to assume that traffic forwarded from the reverse proxy containing the `X-Forwarded-Proto` header with a value of `https` is traffic that originated from the client over https. This information is used internally when processing responses with the `HttpResponseRedirect` class (see [here](https://github.com/mapseed/api/blob/master/src/sa_api_v2/views/base_views.py#L2058-L2063)).
Previously, traffic from the proxy appeared to Django as non-secure, which caused Django to set the `Location` …
> Fix SSL sign-ins

- src/project/settings.py
- src/sa_api_v2/serializers.py
- src/sa_api_v2/tests/test_serializers.py
I think for this to work, once it's merged and deployed we'll have to manually update existing social auths on the api one last time.
> Ensure twitter avatars are fetched over https

- src/sa_api_v2/serializers.py
Addresses: #107, #109, and #110
The `many=True` argument to serializers automatically invokes use of a new DRF class called `ListSerializer` (see [here](http://www.django-rest-framework.org/topics/3.0-announcement/#the-listserializer-class) for the announcement) in DRF3.
This is an issue for our `DataSetSerializer`, which itself has two serializer fields (`DataSetPlaceSetSummarySerializer` and `DataSetSubmissionSetSummarySerializer`) that declare a `many=True` relationship. I think because the model underlying those serializers is a `DataSet`, this generates the error condition we see:
```
'DataSet' object is not iterable
```
Removing the `many=True` kwargs fixes this problem and the corresponding test passes, but I'm unclear if this is actually what we want to be doing here?
> Remove use of many=True kwarg in DataSetSerializer

- src/sa_api_v2/serializers.py
- src/sa_api_v2/views/base_views.py
Addresses: #111
- remove use of deprecated `files` argument to `to_internal_view()`
- use `partial=True` to avoid serializer validation errors
- comment defunct optional serializer method, pending further investigation
> refactor(drf3) fix TestDataSetInstanceView.test_PUT_response

- .travis.yml
- more here: https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
> chore(.travis.yml) use legacy ubuntu trusty for ci

- src/project/settings.py
- src/sa_api_v2/auth_backends.py
Fixes: #128 
Prevent `python-social-auth` from including the dynamic `redirect_state` query param in OAuth requests to Facebook. This allows us to whitelist our domain with Facebook and fixes Facebook logins.
> Fix FB logins

- src/sa_api_v2/models/data_permissions.py
- src/sa_api_v2/serializers.py
- src/sa_api_v2/tests/test_models.py
- src/sa_api_v2/views/base_views.py
Add a data permission check to allow users to edit places that they create when authenticated. This PR would work in conjunction with a corresponding PR on the client that would display the standard editor controls to an authenticated user when they are viewing a place they created.
**Questions**
* There's no way to control allowed methods on this type of permission (e.g. you can't allow `POST` requests and deny `DELETE` requests). In fact, there's no permission model here at all-- we just check that submitter ids match. Is that ok?
* I'm not sure this type of permission makes a lot of difference anyway in common use cases. If I'm understanding the permission system correctly, we need to have a dataset permission that allows `POST` and `DELETE` operations in order for the support button …
> Add place permissions check

- src/sa_api_v2/urls.py
Related to: https://github.com/mapseed/api/issues/139
This PR adds an endpoint that allows us to download a page of our survey data to a file with a `.csv` extension
Note that I tried to rename the downloaded file on the frontend via the `a` tag's `download` attribute, but it doesn't seem possible due to CORS:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes
It seems like the best way to do this was renaming the endpoint on the backend.
> feat(urls.py): add a 'mapseed-places.csv' download route

- src/sa_api_v2/models/data_permissions.py
- src/sa_api_v2/serializers.py
- src/sa_api_v2/tests/test_serializers.py
This PR serializes permissions for each dataset group returned along with the `User` serialization. Group permissions are serialized as an array in the following format:
```
[
{
abilities: ["create", "retrieve", "update", "destroy"],
submission_set: "*"
}
]
```
where each object in the array represents one set of permissions.
We also serialize the `dataset_slug` of each group's parent dataset.
> refactor(GroupSerializer): serialize group permissions and dataset slug

- src/sa_api_v2/serializers.py
This allows our tag endpoints to return a `children` attribute, containing an array of tag id's.
> feat(TagSerializer): return children id's

- src/sa_api_v2/views/base_views.py
Closes: https://github.com/jalMogo/mgmt/issues/227
This PR prevents the API from updating the `submitter` of a place when making a `PUT` request. There is no use case I can think of for an editor updating the original submitter of a Place.
> fix(PlaceInstanceView): don't update the submitter on PUT requests
